### ISSUE TITLE
Port documented as 8000, listens on 8080

### ISSUE THREAD

**Issue by kylecordes** [cyclejs-community/create-cycle-app#111]
**To reproduce the issue:**

Create a fresh app using `cycle-scripts-one-fits-all`.

`npm start`

**Expected behavior:**

Serves on documented port.

**Actual behavior:**

Documentation: "Open your browser at http://localhost:8000 to see your app."

Actual: serves on port 8080 (and emits message saying so).

**Versions of packages used:**

`"cycle-scripts-one-fits-all": "3.1.1",`

Most ideally, in addition to serving on the documented port (either by changing the documentation or changing the code), it would also accept an option the command line --port (for all flavors) and respect and environment variable PORT is present. Currently though, it is possible to configure the port by editing the project local webpack config with something like:

```
  devServer: {
    port: 9000
  }
```

**Comment by jvanbruegge** [comment]
Fixed in the newest version

**Comment by cortopy** [comment]
It's a small thing but it still happens. Webpack listens on 8080
